apiVersion: v1
kind: ConfigMap
metadata:
    name: plugins-jenkins
data:
    plugins.jenkins.api.url: "https://api.plugins.olblak.com"
    plugins.jenkins.data.file.url: "https://ci.jenkins.io/job/Infra/job/plugin-site-api/job/generate-data/lastSuccessfulBuild/artifact/plugins.json.gzip"
